create table if not exists public.telegram_editorial_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  external_id text,
  status text not null default 'new',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);
create unique index if not exists telegram_editorial_events_external_id_uidx on public.telegram_editorial_events(external_id) where external_id is not null;
create index if not exists telegram_editorial_events_status_idx on public.telegram_editorial_events(status, created_at desc);
alter table public.telegram_editorial_events enable row level security;

create table if not exists public.telegram_publications (
  id bigint generated by default as identity primary key,
  telegram_message_id bigint,
  chat_id text not null,
  title text,
  body text not null,
  status text not null default 'draft',
  scheduled_at timestamptz,
  published_at timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists telegram_publications_schedule_idx on public.telegram_publications(status, scheduled_at);
alter table public.telegram_publications enable row level security;

create table if not exists public.telegram_comment_queue (
  id bigint generated by default as identity primary key,
  telegram_update_id bigint,
  chat_id text,
  message_id bigint,
  author_id bigint,
  text text not null,
  route text not null,
  status text not null default 'queued',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists telegram_comment_queue_status_idx on public.telegram_comment_queue(status, created_at desc);
alter table public.telegram_comment_queue enable row level security;

create table if not exists public.telegram_metrics_daily (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  views bigint not null default 0,
  reactions bigint not null default 0,
  comments bigint not null default 0,
  forwards bigint not null default 0,
  new_subscribers bigint not null default 0,
  created_at timestamptz not null default now()
);
alter table public.telegram_metrics_daily enable row level security;
